name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify build files
        run: |
          echo "Current working directory:"
          pwd
          echo "Files in current directory:"
          ls -la
          echo "Files in nextbuild directory:"
          ls -la nextbuild
          echo "Files in nextbuild/server/app directory:"
          ls -la nextbuild/server/app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONALACCESSTOKEN }}
          publish_dir: ./nextbuild/server/app
